name: Run BOT-JS1.6.0

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Clone BOT-JS1.6.0
        run: git clone https://github.com/depchaiaiyeu/BOT-JS1.6.0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg
        
      - name: Install dependencies & replace nsfwjs
        run: |
          cd BOT-JS1.6.0
          npm install
          rm -rf node_modules/nsfwjs
          cp -r nsfwjs.u node_modules/nsfwjs

      - name: Run bot
        run: |
          cd BOT-JS1.6.0
          node bot.js
